# Generated by Django 4.1.5 on 2023-01-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_perevalareas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevalareas',
            old_name='ip_parent',
            new_name='id_parent',
        ),
    ]
