# Generated by Django 4.1.5 on 2023-01-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_rename_ip_parent_perevalareas_id_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
