# Generated by Django 4.1.5 on 2023-01-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0007_alter_images_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('2', 'pending'), ('4', 'rejected'), ('1', 'new'), ('3', 'accepted')], default='new', max_length=8),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_autumn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_spring',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_summer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_winter',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
