# Generated by Django 4.1.5 on 2023-02-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0011_alter_perevaladded_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMGTEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.BinaryField()),
            ],
        ),
    ]
