# Generated by Django 4.1.5 on 2023-02-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0012_imgtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgtest',
            name='new',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imgtest',
            name='img',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('2', 'pending'), ('4', 'rejected'), ('1', 'new'), ('3', 'accepted')], default='new', max_length=8),
        ),
    ]
