# Generated by Django 4.1.5 on 2023-02-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0014_remove_imgtest_img_remove_imgtest_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgtest',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('3', 'accepted'), ('4', 'rejected'), ('1', 'new'), ('2', 'pending')], default='new', max_length=8),
        ),
    ]
